=== hannahcgunderman/INSC524-DMPCore/XSDFinal.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="record">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="fundAgency"/>
        <xs:element maxOccurs="unbounded" ref="template" minOccurs="0"/>
        <xs:element ref="staffWrap"/>
        <xs:element ref="date"/>
        <xs:element maxOccurs="unbounded" ref="analysisUnit"/>
        <xs:element maxOccurs="unbounded" ref="storage"/>
        <xs:element ref="description" minOccurs="0"/>
        <xs:element maxOccurs="unbounded" ref="domain"/>
        <xs:element ref="analysisWrap"/>
        <xs:element ref="embargoes" minOccurs="0"/>
        <xs:element maxOccurs="unbounded" ref="dataType"/>
        <xs:element ref="byteSize" maxOccurs="unbounded"/>
        <xs:element ref="rightsReuseWrap"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="fundAgency">
    <xs:complexType mixed="true">
      <xs:attribute name="termsource" use="required" type="xs:NCName"/>
      <xs:attribute name="termsourceid" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="template" type="xs:string"/>
  <xs:element name="staffWrap">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="creator"/>
        <xs:element maxOccurs="unbounded" ref="PI"/>
        <xs:element maxOccurs="unbounded" ref="contributor" minOccurs="0"/>
        <xs:element maxOccurs="unbounded" ref="affiliation"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="creator">
    <xs:complexType mixed="true">
      <xs:attribute name="termsource" use="required" type="xs:NCName"/>
      <xs:attribute name="termsourceid" use="required" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="PI">
    <xs:complexType mixed="true">
      <xs:attribute name="termsource" use="required" type="xs:NCName"/>
      <xs:attribute name="termsourceid" use="required" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="contributor">
    <xs:complexType mixed="true">
      <xs:attribute name="termsource" use="required" type="xs:NCName"/>
      <xs:attribute name="termsourceid" use="required" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="affiliation">
    <xs:complexType mixed="true">
      <xs:attribute name="termsource" use="required" type="xs:NCName"/>
      <xs:attribute name="termsourceid" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="date">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:integer">
          <xs:attribute name="termsource" use="required"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="analysisUnit">
    <xs:complexType mixed="true">
      <xs:attribute name="termsource" use="required" type="xs:NCName"/>
      <xs:attribute name="termsourceid" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="storage" type="xs:string"/>
  <xs:element name="description" type="xs:string"/>
  <xs:element name="domain">
    <xs:complexType mixed="true">
      <xs:attribute name="termsource" use="required" type="xs:NCName"/>
      <xs:attribute name="termsourceid" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="analysisWrap">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="softwarePackage"/>
        <xs:element ref="analysisType" maxOccurs="unbounded" minOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="softwarePackage">
    <xs:complexType mixed="true">
      <xs:attribute name="termsource" use="required" type="xs:NCName"/>
      <xs:attribute name="termsourceid" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="analysisType">
    <xs:complexType mixed="true">
      <xs:attribute name="termsource" use="required" type="xs:NCName"/>
      <xs:attribute name="termsourceid" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="embargoes" type="xs:string"/>
  <xs:element name="dataType">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:NCName">
          <xs:attribute name="termsource" use="required" type="xs:NCName"/>
          <xs:attribute name="termsourceid" use="required" type="xs:NCName"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="byteSize">
    <xs:complexType mixed="true">
      <xs:attribute name="termsource" use="required" type="xs:NCName"/>
      <xs:attribute name="termsourceid" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="rightsReuseWrap">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="accessRights"/>
        <xs:element ref="rights"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="accessRights" type="xs:string"/>
  <xs:element name="rights" type="xs:string"/>
</xs:schema>

=== hannahcgunderman/INSC524-DMPCore/XMLFinal.xml
<?xml version="1.0" encoding="UTF-8"?>
<record xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/C:/Users/Leah/Desktop/MSIS/INSC524%20Metadata/Assignment4/XSDFinal.xsd">
    <fundAgency termsource="LCNAF" termsourceid="n2006182431">National Science Foundation (U.S.). Subcommittee on Nanoscale Science, Engineering, and Technology</fundAgency>
    <template>DMP Tool</template>
    <template>Reynholm Industries Internal Template</template>
    <staffWrap>
        <creator termsource="local" termsourceid="0118">Avenal, Richmond</creator>
        <creator termsource="local" termsourceid="999">second creator</creator>
        <PI termsource="local" termsourceid="881">Barber, Jen</PI>
        <PI termsource="local" termsourceid="999">Reynholm, Denholm</PI>
        <contributor termsource="local" termsourceid="119">Moss, Maurice</contributor>
        <contributor termsource="local" termsourceid="725">Trenneman, Roy</contributor>
        <contributor termsource="local" termsourceid="3">Reynholm, Douglas</contributor>
        <affiliation termsource="LCNAF" termsourceid="n2001131100">Channel 4 International</affiliation>
        <affiliation termsource="local" termsourceid="IT">Information Technology</affiliation>
    </staffWrap>
    <date termsource="ISO 8601">20180910</date>
    <analysisUnit termsource="LCNAF" termsourceid="sh85035858">Data processing service centers</analysisUnit>
    <storage>Reynholm Industries</storage>
    <storage>Internet Repository</storage>
    <description>"This project documents the steps used to create The Internet"</description>
    <domain termsource="LCSH" termsourceid="sh89003285">Computer science</domain>
    <domain termsource="LCSH" termsourceid="sh87002293">Information technology</domain>
    <analysisWrap>
        <softwarePackage termsource="local" termsourceid="R">R</softwarePackage>
        <softwarePackage termsource="local" termsourceid="SPS5">Statistical Package for Social Sciences (SPSS)</softwarePackage>
        <analysisType termsource="LCSH" termsourceid="sh85012506">Bayesian statistical decision theory</analysisType>
    </analysisWrap>
    <embargoes>"The public will have access to the raw data one year after the project funding window closes."</embargoes>
    <dataType termsource="LCSH" termsourceid="sh2007000909">Quantitative</dataType>
    <dataType termsource="LCSH" termsourceid="sh99004969">Qualitative</dataType>
    <byteSize>4 TB</byteSize>
    <rightsReuseWrap>
        <accessRights>"This DMP may be reused with attribution to creator Matt Berry"</accessRights>
        <rights>"The public will have access to aggregate data tables"</rights>
    </rightsReuseWrap>
</record>
